### ISSUE TITLE
Error: `Import or export declaration in an ambient module declaration cannot reference module through relative module name.`

### ISSUE THREAD

**Issue by Niek** [muratgozel/locale-util#8]
I see this issue:
<img width="993" alt="Screenshot 2023-03-22 at 11 47 07" src="https://user-images.githubusercontent.com/213140/226880591-1556641b-f024-47c6-8045-64767e0856ed.png">

**Comment by muratgozel** [comment]
ah okay, sorting it out, sorry for this.

**Comment by Niek** [comment]
No worries! BTW, importing from CJS code is also not supported now:
```
const { findCountryTimezones } = require('locale-util')
                                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module ./node_modules/locale-util/dist/cjs/index.js from blah.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ./node_modules/locale-util/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/blah.js:26:34) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by muratgozel** [comment]
Hi @Niek just published the new release (3.0.3), could you check if these problems still occur?

**Comment by Niek** [comment]
@muratgozel The good news is that it works from CJS code now!

The bad news is that it spawns my IDE with loads of TS issues 😄  See below:
<img width="821" alt="Screenshot 2023-03-29 at 21 39 33" src="https://user-images.githubusercontent.com/213140/228649426-8a8df149-083e-47be-ab4e-c702bf61896a.png">


<img width="1235" alt="Screenshot 2023-03-29 at 21 40 50" src="https://user-images.githubusercontent.com/213140/228649688-8f5cfd65-82a7-4f27-8ff3-909240a713d6.png">

Please let me know if you need more info.

**Comment by muratgozel** [comment]
@Niek omg so sorry 😬 im trying something new with typescript, just updated the package (3.0.6), could you now check it everything is okay?

**Comment by Niek** [comment]
No worries @muratgozel - interop between JS/TS/CJS/etc is a mess 😄 

I can confirm the errors are gone! Just one small thing: importing the function in a CJS file gives a tslint warning:

<img width="606" alt="Screenshot 2023-03-30 at 12 44 51" src="https://user-images.githubusercontent.com/213140/228812402-bd0db71f-4f0a-4150-bfbd-f319ab39d04c.png">

Which is strange because it's definitely being used. I also somehow can't see the type of the function when hovering it, while the `index.d.ts` type looks correct.

**Comment by muratgozel** [comment]
@Niek yes the editor wasnt able to resolve the types, i guess the trick is adding `export as namespace localeUtil` for cjs. updated the package. im able to see the functions now thorugh ctrl+click. do you?

<img width="920" alt="Screen Shot 2023-03-30 at 15 27 03" src="https://user-images.githubusercontent.com/15162371/228836288-a11e26fc-7d2f-4ab7-8a1c-80de1bd5f90e.png">

**Comment by Niek** [comment]
A different error this time, I'm afraid:
<img width="551" alt="Screenshot 2023-03-30 at 15 03 33" src="https://user-images.githubusercontent.com/213140/228844699-579dd1a6-7ca7-4185-892d-d83ebe0fb15d.png">

**Comment by muratgozel** [comment]
@Niek okay, it seems like the recommended way to create declarations is `declare module` and commonjs environment doesn't fully compatible with that. i have updated one more time with (even) better typings. how does it look like in your end? 👀 

Share your typescript version and config with me please if you are unhappy with the result.

**Comment by Niek** [comment]
Thanks @muratgozel! I see no more errors, other than that `@tsconfig/node18-strictest-esm` should be added as a (dev?)dependency.

My tslint keeps complaining though, this is in a non-TS project with just CJS files. Here is a quick reproducible sample:
`package.json`:
```json
{
  "dependencies": {
    "locale-util": "^3.0.8"
  }
}
```

`test.js`:
```js
const { findCountryTimezones } = require('locale-util')

console.log(findCountryTimezones('us'))
```

In vscode (default settings):
<img width="688" alt="Screenshot 2023-03-30 at 16 44 28" src="https://user-images.githubusercontent.com/213140/228873743-d30a8a80-0fe9-44bb-9ade-f8f39a61ed0c.png">

**Comment by muratgozel** [comment]
@Niek how is it looking now?

**Comment by Niek** [comment]
You did it @muratgozel! All fixed now, thanks a lot!

<img width="647" alt="Screenshot 2023-03-30 at 18 40 50" src="https://user-images.githubusercontent.com/213140/228905997-5edebded-228d-4f52-a735-0ca277253508.png">

**Comment by Niek** [comment]
<img width="488" alt="Screenshot 2023-03-30 at 18 42 32" src="https://user-images.githubusercontent.com/213140/228906361-81580daf-efe4-49eb-b62d-f60b67400359.png">

Just one small complaint on the tsconfig

**Comment by muratgozel** [comment]
Thanks for the collaboration @Niek 🙏 im grateful.

Yes, my editor also raises that warning. Its because editors arent yet ready for typescript 5. It will be gone in the coming editor updates 😌
